set encoding=utf-8
set t_Co=256
set shell=bash
set nocompatible " be iMproved
filetype off     " required!

set rtp+=~/.vim/bundle/vundle/
call vundle#rc()
Bundle 'gmarik/vundle'
if filereadable(expand('~/.vim/Vunfile'))
  source ~/.vim/Vunfile
endif
if filereadable(expand('~/.vim/vimrc.local'))
  source ~/.vim/vimrc.local
endif

